default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: workshare_test_development

test:
  <<: *default
  database: workshare_test_test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: workshare_test_production
  username: workshare_test
  password: <%= ENV['WORKSHARE_TEST_DATABASE_PASSWORD'] %>

